# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/chris/Repos/EmbeddedSystems/Zynq_Book/first_zynq_design/first_zynq_design.srcs/sources_1/bd/first_zynq_system/ip/first_zynq_system_axi_gpio_0_0/first_zynq_system_axi_gpio_0_0.xci
# IP: The module: 'first_zynq_system_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/chris/Repos/EmbeddedSystems/Zynq_Book/first_zynq_design/first_zynq_design.srcs/sources_1/bd/first_zynq_system/ip/first_zynq_system_axi_gpio_0_0/first_zynq_system_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'first_zynq_system_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/chris/Repos/EmbeddedSystems/Zynq_Book/first_zynq_design/first_zynq_design.srcs/sources_1/bd/first_zynq_system/ip/first_zynq_system_axi_gpio_0_0/first_zynq_system_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'first_zynq_system_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/chris/Repos/EmbeddedSystems/Zynq_Book/first_zynq_design/first_zynq_design.srcs/sources_1/bd/first_zynq_system/ip/first_zynq_system_axi_gpio_0_0/first_zynq_system_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'first_zynq_system_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/chris/Repos/EmbeddedSystems/Zynq_Book/first_zynq_design/first_zynq_design.srcs/sources_1/bd/first_zynq_system/ip/first_zynq_system_axi_gpio_0_0/first_zynq_system_axi_gpio_0_0.xci
# IP: The module: 'first_zynq_system_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/chris/Repos/EmbeddedSystems/Zynq_Book/first_zynq_design/first_zynq_design.srcs/sources_1/bd/first_zynq_system/ip/first_zynq_system_axi_gpio_0_0/first_zynq_system_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'first_zynq_system_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/chris/Repos/EmbeddedSystems/Zynq_Book/first_zynq_design/first_zynq_design.srcs/sources_1/bd/first_zynq_system/ip/first_zynq_system_axi_gpio_0_0/first_zynq_system_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'first_zynq_system_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/chris/Repos/EmbeddedSystems/Zynq_Book/first_zynq_design/first_zynq_design.srcs/sources_1/bd/first_zynq_system/ip/first_zynq_system_axi_gpio_0_0/first_zynq_system_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'first_zynq_system_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
