# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/interrupt_switch_design/interrupt_switch_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==interrupt_switch_design || ORIG_REF_NAME==interrupt_switch_design} -quiet] -quiet

# IP: bd/interrupt_switch_design/ip/interrupt_switch_design_processing_system7_0_0/interrupt_switch_design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==interrupt_switch_design_processing_system7_0_0 || ORIG_REF_NAME==interrupt_switch_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/interrupt_switch_design/ip/interrupt_switch_design_axi_gpio_0_0/interrupt_switch_design_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==interrupt_switch_design_axi_gpio_0_0 || ORIG_REF_NAME==interrupt_switch_design_axi_gpio_0_0} -quiet] -quiet

# IP: bd/interrupt_switch_design/ip/interrupt_switch_design_ps7_0_axi_periph_0/interrupt_switch_design_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==interrupt_switch_design_ps7_0_axi_periph_0 || ORIG_REF_NAME==interrupt_switch_design_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/interrupt_switch_design/ip/interrupt_switch_design_rst_ps7_0_100M_0/interrupt_switch_design_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==interrupt_switch_design_rst_ps7_0_100M_0 || ORIG_REF_NAME==interrupt_switch_design_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/interrupt_switch_design/ip/interrupt_switch_design_xlconcat_0_0/interrupt_switch_design_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==interrupt_switch_design_xlconcat_0_0 || ORIG_REF_NAME==interrupt_switch_design_xlconcat_0_0} -quiet] -quiet

# IP: bd/interrupt_switch_design/ip/interrupt_switch_design_axi_gpio_1_0/interrupt_switch_design_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==interrupt_switch_design_axi_gpio_1_0 || ORIG_REF_NAME==interrupt_switch_design_axi_gpio_1_0} -quiet] -quiet

# IP: bd/interrupt_switch_design/ip/interrupt_switch_design_axi_gpio_2_0/interrupt_switch_design_axi_gpio_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==interrupt_switch_design_axi_gpio_2_0 || ORIG_REF_NAME==interrupt_switch_design_axi_gpio_2_0} -quiet] -quiet

# IP: bd/interrupt_switch_design/ip/interrupt_switch_design_axi_timer_0_0/interrupt_switch_design_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==interrupt_switch_design_axi_timer_0_0 || ORIG_REF_NAME==interrupt_switch_design_axi_timer_0_0} -quiet] -quiet

# IP: bd/interrupt_switch_design/ip/interrupt_switch_design_xbar_0/interrupt_switch_design_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==interrupt_switch_design_xbar_0 || ORIG_REF_NAME==interrupt_switch_design_xbar_0} -quiet] -quiet

# IP: bd/interrupt_switch_design/ip/interrupt_switch_design_auto_pc_0/interrupt_switch_design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==interrupt_switch_design_auto_pc_0 || ORIG_REF_NAME==interrupt_switch_design_auto_pc_0} -quiet] -quiet

# XDC: bd/interrupt_switch_design/interrupt_switch_design_ooc.xdc
