# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/chris/Repos/EmbeddedSystems/CC__LED_BUTTON/CC__LED_BUTTON.srcs/sources_1/bd/zynq_LED_system/ip/zynq_LED_system_axi_gpio_0_0/zynq_LED_system_axi_gpio_0_0.xci
# IP: The module: 'zynq_LED_system_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/chris/Repos/EmbeddedSystems/CC__LED_BUTTON/CC__LED_BUTTON.srcs/sources_1/bd/zynq_LED_system/ip/zynq_LED_system_axi_gpio_0_0/zynq_LED_system_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_LED_system_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/chris/Repos/EmbeddedSystems/CC__LED_BUTTON/CC__LED_BUTTON.srcs/sources_1/bd/zynq_LED_system/ip/zynq_LED_system_axi_gpio_0_0/zynq_LED_system_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_LED_system_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/chris/Repos/EmbeddedSystems/CC__LED_BUTTON/CC__LED_BUTTON.srcs/sources_1/bd/zynq_LED_system/ip/zynq_LED_system_axi_gpio_0_0/zynq_LED_system_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_LED_system_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/chris/Repos/EmbeddedSystems/CC__LED_BUTTON/CC__LED_BUTTON.srcs/sources_1/bd/zynq_LED_system/ip/zynq_LED_system_axi_gpio_0_0/zynq_LED_system_axi_gpio_0_0.xci
# IP: The module: 'zynq_LED_system_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/chris/Repos/EmbeddedSystems/CC__LED_BUTTON/CC__LED_BUTTON.srcs/sources_1/bd/zynq_LED_system/ip/zynq_LED_system_axi_gpio_0_0/zynq_LED_system_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_LED_system_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/chris/Repos/EmbeddedSystems/CC__LED_BUTTON/CC__LED_BUTTON.srcs/sources_1/bd/zynq_LED_system/ip/zynq_LED_system_axi_gpio_0_0/zynq_LED_system_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_LED_system_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/chris/Repos/EmbeddedSystems/CC__LED_BUTTON/CC__LED_BUTTON.srcs/sources_1/bd/zynq_LED_system/ip/zynq_LED_system_axi_gpio_0_0/zynq_LED_system_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_LED_system_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
