# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/first_zynq_system/first_zynq_system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==first_zynq_system || ORIG_REF_NAME==first_zynq_system} -quiet] -quiet

# IP: bd/first_zynq_system/ip/first_zynq_system_processing_system7_0_0/first_zynq_system_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==first_zynq_system_processing_system7_0_0 || ORIG_REF_NAME==first_zynq_system_processing_system7_0_0} -quiet] -quiet

# IP: bd/first_zynq_system/ip/first_zynq_system_axi_gpio_0_0/first_zynq_system_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==first_zynq_system_axi_gpio_0_0 || ORIG_REF_NAME==first_zynq_system_axi_gpio_0_0} -quiet] -quiet

# IP: bd/first_zynq_system/ip/first_zynq_system_ps7_0_axi_periph_0/first_zynq_system_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==first_zynq_system_ps7_0_axi_periph_0 || ORIG_REF_NAME==first_zynq_system_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/first_zynq_system/ip/first_zynq_system_rst_ps7_0_100M_0/first_zynq_system_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==first_zynq_system_rst_ps7_0_100M_0 || ORIG_REF_NAME==first_zynq_system_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/first_zynq_system/ip/first_zynq_system_auto_pc_0/first_zynq_system_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==first_zynq_system_auto_pc_0 || ORIG_REF_NAME==first_zynq_system_auto_pc_0} -quiet] -quiet

# XDC: bd/first_zynq_system/first_zynq_system_ooc.xdc
