# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/chris/Repos/EmbeddedSystems/Lab2/Interrupts_switches/Interrupts_switches.srcs/sources_1/bd/interrupt_switch_design/ip/interrupt_switch_design_processing_system7_0_0/interrupt_switch_design_processing_system7_0_0.xci
# IP: The module: 'interrupt_switch_design_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/chris/Repos/EmbeddedSystems/Lab2/Interrupts_switches/Interrupts_switches.srcs/sources_1/bd/interrupt_switch_design/ip/interrupt_switch_design_processing_system7_0_0/interrupt_switch_design_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'interrupt_switch_design_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/chris/Repos/EmbeddedSystems/Lab2/Interrupts_switches/Interrupts_switches.srcs/sources_1/bd/interrupt_switch_design/ip/interrupt_switch_design_processing_system7_0_0/interrupt_switch_design_processing_system7_0_0.xci
# IP: The module: 'interrupt_switch_design_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/chris/Repos/EmbeddedSystems/Lab2/Interrupts_switches/Interrupts_switches.srcs/sources_1/bd/interrupt_switch_design/ip/interrupt_switch_design_processing_system7_0_0/interrupt_switch_design_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'interrupt_switch_design_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
